language: shell
services:
  - docker
env:
  global:
    - IMAGE_NAME=devops-example:latest
    - REGISTRY_SERVER=us.icr.io
script:
  - docker build -t ${IMAGE_NAME} .
  - docker run -it --entrypoint /bin/bash ${IMAGE_NAME} -c pytest unit_test
after_success:
  - docker login -u iamapikey -p "${IBM_CLOUD_API_KEY}" ${REGISTRY_SERVER}
  - docker push ${IMAGE_NAME}
  - curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
  - ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r us-south
  - ibmcloud target --cf
  - ibmcloud cf install
  - ibmcloud cf push
  - echo "Finished"